markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: 倦赴博客
subTitle: things don't change,but people do..
description: 在这里，不仅仅是用来快速记录工作，学习，生活的一点一滴的地方，更是 头子 对 Jekyll 的学习和使用的一次有意义的实践。
url: http://h539251932.github.io/mohao
feed: /atom.xml
#个人信息的配置
qq: 305749023
name: 就叫我"mohao"吧
email: h539251932@qq.com
github: h539251932
about: "这里是 mohao 的个人博客，创建于 2021 年。<br />
#菜单配置
nav:
  - text: 首页
    url: /ibnew/index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /ibnew/archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /ibnew/contact.html
    #url: /ibnew/about/
    icon: icon-envelope-alt
    class: none
  - text: 联系我
    url: https://twitter.com/policetouzi
    icon: icon-heart
    class: none
  - text: 博客源代码
    url: https://github.com/touzi/ibnew
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: touzi
